spring:
  profiles:
    active: "dev"
    group:
      "dev": "dev"
      "prod": "prod" #\u7528\u6765\u533A\u522Bswagger3\u662F\u5426\u751F\u6548

---
server:
  port: 8100

spring:
  config:
    activate:
      on-profile: "dev"
  application:
    name: bgzMusic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://120.77.144.44:3306/bgzMusic?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Cheng1000!
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      max-wait-millis: 150 #\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
      max-total: 5 #\u6700\u5927\u8FDE\u63A5\u6570
      initial-size: 5 #\u521D\u59CB\u5316\u8FDE\u63A5\u6570

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml  #\u6620\u5C04\u6587\u4EF6\u4F4D\u7F6E
  configuration:
    map-underscore-to-camel-case: true  #\u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u6CD5
    cache-enabled: true #\u5F00\u542F\u4E8C\u7EA7\u7F13\u5B58\uFF0C\u8FD8\u9700\u8981\u5BF9xml\u53CA\u5176\u5BF9\u5E94\u65B9\u6CD5\u6DFB\u52A0\u5F00\u542F(\u4E8C\u7EA7\u7F13\u5B58\u5E38\u7528\u4E8E\u4E0D\u7ECF\u5E38\u6539\u52A8\u7684\u6570\u636E\uFF0C\u6216\u6539\u52A8\u5F71\u54CD\u4E0D\u5927)
  type-aliases-package: com.cxb.bgz.entity  #\u522B\u540D

---
server:
  port: 8200

spring:
  config:
    activate:
      on-profile: "prod"
  application:
    name: bgzMusic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://120.77.144.44:3306/bgzMusic?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Cheng1000!
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      max-wait-millis: 150 #\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
      max-total: 5 #\u6700\u5927\u8FDE\u63A5\u6570
      initial-size: 5 #\u521D\u59CB\u5316\u8FDE\u63A5\u6570

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml  #\u6620\u5C04\u6587\u4EF6\u4F4D\u7F6E
  configuration:
    map-underscore-to-camel-case: true  #\u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u6CD5
    cache-enabled: true #\u5F00\u542F\u4E8C\u7EA7\u7F13\u5B58\uFF0C\u8FD8\u9700\u8981\u5BF9xml\u53CA\u5176\u5BF9\u5E94\u65B9\u6CD5\u6DFB\u52A0\u5F00\u542F(\u4E8C\u7EA7\u7F13\u5B58\u5E38\u7528\u4E8E\u4E0D\u7ECF\u5E38\u6539\u52A8\u7684\u6570\u636E\uFF0C\u6216\u6539\u52A8\u5F71\u54CD\u4E0D\u5927)
  type-aliases-package: com.cxb.bgz.entity  #\u522B\u540D
